version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    ports:
      - "5173:5173"
