version: "3.8"
services:
  backend-user-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.UserService
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/UserService:/app/src
  backend-course-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.CourseService
    ports:
      - "8081:8081"
    volumes:
      - ./backend/src/CourseService:/app/src
  backend-course-search-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.CourseSearchService
    ports:
      - "8082:8082"
    volumes:
      - ./backend/src/CourseSearchService:/app/src
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./frontend/src:/app/src
  #   depends_on:
  #     - backend-user-service
  #     - backend-course-service
  #     - backend-course-search-service
  #   ports:
  #     - "5173:5173"

