trigger:
  branches:
    include:
    - main
    - develop

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'dhacr01'
  imageRepository: 'darshubbackend'
  containerRegistry: 'dhacr01.azurecr.io'
  
  # master branch -->  prod builds
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    tag: 'prod'
  # develop branch --> dev builds
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    tag: 'dev'

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Docker@2
  displayName: Build an image 
  inputs:
    command: build
    repository: $(imageRepository)
    dockerfile: 'backend/Dockerfile'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
- task: Docker@2
  displayName: Push an image to container registry
  inputs:
    command: push
    repository: $(imageRepository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)