trigger:
  branches:
    include:
    - main
    - develop

  paths:
    include:
    - backend

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: dhacr01
  imageRepository: darshubbackend
  containerRegistry: dhacr01.azurecr.io
  
  # master branch -->  prod builds
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    tag: prod
  # develop branch --> dev builds
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    tag: dev

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build an image 
  inputs:
    command: build
    repository: $(imageRepository)
    dockerfile: backend/Dockerfile.CourseService
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
- task: Docker@2
  inputs:
    containerRegistry: 'dhacr01'
    command: 'login'
    arguments: |
      --client-secret $DOCKER_ACR_PW

- task: AzureCLI@2
  inputs:
    azureSubscription: 'DarsHub-Subs-VSES (3c92a5d0-71e6-4e4f-888c-c23d10563f00)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login;
      az acr login --name $containerRegistry

- task: Docker@2
  displayName: Push an image to container registry
  inputs:
    command: push
    repository: $(imageRepository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)