trigger:
  branches:
    include:
    - main
    - develop
        
  paths:
    include:
    - frontend

pool:
  vmImage: 'ubuntu-latest'

variables:
  # master branch -->  prod builds
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    buildConfig: prod
  # develop branch --> dev builds
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    buildConfig: dev

steps:
  - task: Npm@1
    inputs:
      command: custom
      customCommand: ci
      workingDir: '$(Build.SourcesDirectory)/frontend'
    displayName: 'npm ci'

  - script: |
      cd frontend
      npm run build:$(buildConfig)
    displayName: 'Build -$(buildConfig)- frontend'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: frontend/dist
      includeRootFolder: false    
      replaceExistingArchive: true  
    displayName: 'Archive dist'
      
  - task: PublishBuildArtifacts@1
    inputs: 
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: dist
    displayName: 'Publish artifact'
