# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - services/pdf-generator

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Debug'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: UseDotNet@2
  inputs:
    version: '7.x'
    includePreviewVersions: false # Required for preview versions
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
    projects: 'tests' # update with your test project directory

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: frontend/dist
    includeRootFolder: false    
    replaceExistingArchive: true  
  displayName: 'Archive dist'
    
- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'dist'
  displayName: 'Publish artifact'